FROM python:3.11-slim

WORKDIR /app

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./assignment_3/app_fastapi .

EXPOSE 8050

CMD ["uvicorn", "fastapi_app:app", "--host", "0.0.0.0", "--port", "8050"]
