services:
  base:
    build:
      context: ../
      dockerfile: ./assignment_3/Dockerfile
    image: nlp-cpu-env

  fastapi:
    image: nlp-cpu-env
    working_dir: /app/app_fastapi
    ports:
      - "8050:8050"
    command: uvicorn fastapi_app:app --host=0.0.0.0 --port=8050
  
  streamlit:
    image: nlp-cpu-env
    working_dir: /app/app_streamlit
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0

  flask-networked:
    image: nlp-cpu-env
    working_dir: /app/app_flask
    ports:
      - "8000:8000"
    command: python app_flask.py
    environment:
      MYSQL_HOST: sql_db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: mydatabase
  
  sql_db:
    image: mysql:8.0
    volumes:
      - sql-data-db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
  
volumes:
  sql-data-db:
